# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '1b0c246b-2b8b-4861-a34e-1302a694a704'

  # Function app name
  functionAppName: 'tenant-store-az-dev'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/AzureFunction/TenantStore.API'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: latest

    steps:
    - task: SampleCustomMsg@0
      inputs:
        cwd: '$(workingDirectory)'
        msg: 'Hello World'
